const services={
 hair:{num:'01 · Hair Atelier',time:'45–150 min',title:'Hair that still feels like you.',copy:'Precision cuts, dimensional colour, gloss rituals and restorative care. Every appointment starts with texture, routine and maintenance — not a catalogue photo.',items:[['Cut + finish','from ₹1,800'],['Gloss + tone','from ₹2,400'],['Balayage','from ₹5,500'],['Repair ritual','from ₹2,200']],img:'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=72&w=1400',alt:'Hair wash treatment in a salon',cap:'Hair · consultation first'},
 skin:{num:'02 · Skin Studio',time:'60–90 min',title:'Skin care, minus the hard sell.',copy:'Barrier-first facials and glow treatments built around how your skin behaves today. Calm first, then brighten, hydrate or refine.',items:[['Essential facial','from ₹2,600'],['Sculpt + glow','from ₹3,400'],['Hydration ritual','from ₹3,100'],['Event skin prep','from ₹4,200']],img:'https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=72&w=1400',alt:'Facial skincare treatment',cap:'Skin · barrier-first care'},
 spa:{num:'03 · Spa Rituals',time:'60–120 min',title:'A full stop for your nervous system.',copy:'Warm oils, deliberate pressure, quiet rooms and unhurried transitions. Choose relaxation, recovery or a longer head-to-toe reset.',items:[['Aroma massage','from ₹3,200'],['Deep reset','from ₹3,800'],['Body polish','from ₹2,900'],['ÉLANE Escape','from ₹6,800']],img:'https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=72&w=1400',alt:'Relaxing spa facial treatment',cap:'Spa · slow restorative care'},
 occasion:{num:'04 · Occasion',time:'75–180 min',title:'Ready, without feeling overdone.',copy:'Polished hair, skin prep and makeup with enough time to adjust. Built for dinners, shoots, weddings and everything photographed.',items:[['Event hair','from ₹2,800'],['Soft glam','from ₹3,500'],['Hair + makeup','from ₹5,800'],['Bridal preview','from ₹4,500']],img:'https://images.unsplash.com/photo-1722935408489-2bf93349c8cb?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=72&w=1400',alt:'Hair styling detail in salon',cap:'Occasion · polished, not overdone'}
};
const panel={num:document.getElementById('serviceNum'),time:document.getElementById('serviceTime'),title:document.getElementById('serviceTitle'),copy:document.getElementById('serviceCopy'),list:document.getElementById('serviceList'),img:document.getElementById('serviceImage'),cap:document.getElementById('serviceCaption')};
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const s=services[btn.dataset.service];panel.num.textContent=s.num;panel.time.textContent=s.time;panel.title.textContent=s.title;panel.copy.textContent=s.copy;panel.list.innerHTML=s.items.map(i=>`<div><b>${i[0]}</b><small>${i[1]}</small></div>`).join('');panel.img.src=s.img;panel.img.alt=s.alt;panel.cap.textContent=s.cap;}));
const recs={reset:['The ÉLANE Escape','90-minute body massage + express facial + scalp ritual. Slow, restorative, no overthinking.'],glow:['Sculpt + Glow Facial','A skin-first facial with gentle resurfacing, facial massage and hydration for an immediate polished finish.'],hair:['Repair + Gloss Ritual','Repair treatment, scalp massage and gloss service for softer texture and cleaner shine.'],event:['Event Ready, Slowly','Skin preparation, polished hair and soft-glam makeup planned as one calm appointment.']};
document.querySelectorAll('.qopt').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.qopt').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const r=recs[btn.dataset.rec];document.getElementById('recTitle').textContent=r[0];document.getElementById('recCopy').textContent=r[1];}));
const dialog=document.getElementById('bookingDialog');document.querySelectorAll('.js-book').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
